#!/usr/bin/env bash

# Bspwm maain config file
pgrep -x sxhkd > /dev/null || sxhkd &

export PATH="$HOME/.config/bspwm/scripts:$PATH"

# Killing processes

processes=("sxhkd" "polybar" "dunst" "xfce4-clipman")

	for process in "${processes[@]}"; do
		if pgrep -f "$process"; then
			pkill -9 -f "$process" > /dev/null; sleep 0.1
		fi
	done


# Bspwm Configuration

bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8'
bspc config window_gap                16
bspc config split_ratio               0.5
bspc config single_monocle            true 
bspc config borderless_monocle        true 
bspc config gapless_monocle           false 
bspc config automatic_scheme          alternate 

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_motion_interval   5
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner
bspc config border_width              0
bspc config top_padding               0
bspc config left_padding              0
bspc config right_padding             0
bspc config normal_border_color       "#0a0a0a"
bspc config focused_border_color      "#bdcaf2"
bspc config presel_feedback_color     "#7aa2f7"

# Autostart 

pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/sxhkdrc & }
pidof -q xset || { xset r rate 200 25 & }
pidof -q polybar || { polybar --config="${HOME}"/.config/bspwm/polybar/config.ini & }
pidof -q picom || { picom --config "${HOME}"/.config/bspwm/picom/picom.conf & }
pidof -q dunst || { dunst -config "${HOME}"/.config/bspwm/dunstrc & }
pidof -q xfce4-clipman || { xfce4-clipman & }
feh --bg-fill "${HOME}"/.config/bspwm/assets/wallpaper_main.jpg &

while true; do
  xset r rate 200 25
  sleep 60
done
