#!/usr/bin/env bash
# SCRIPTS

WIDGET_DIR="$HOME/.config/bspwm/eww"
TERMINAL="kitty"

case "$1" in
    --menu)
        rofi -show drun -theme "$HOME"/.config/bspwm/src/rofi-themes/Launcher.rasi 
        ;;
    --terminal)
        kitty 
        ;;
    --update)
        Term --update
        ;;
    --checkupdates)
        Term --checkupdates
        ;;
    *)
        echo "Invalid Option"
        ;;
esac
