#!/usr/bin/env bash
# Main var
MY_TERM="alacritty"
CONFIG_PATH_KITTY="$HOME/.config/bspwm/kitty/kitty.conf"
CONFIG_PATH_ALACRITTY="$HOME/.config/bspwm/alacritty/alacritty.toml"

case $MY_TERM in
    "alacritty")
        case $1 in
            "--terminal")
                alacritty --config-file "$CONFIG_PATH_ALACRITTY"
                ;;
            "--floating")
                alacritty --config-file "$CONFIG_PATH_ALACRITTY" --class FloaTerm,FloaTerm
                ;;
            "--update")
                alacritty --config-file "$CONFIG_PATH_ALACRITTY" --hold --class FloaTerm,FloaTerm -e Updates --update-system
                ;;
            "--checkupdates")
                alacritty --config-file "$CONFIG_PATH_ALACRITTY" --hold --class Updating,Updating -e Updates --print-updates
                ;;
            "--ranger")
                alacritty --config-file "$CONFIG_PATH_ALACRITTY" --class RangerTerm,RangerTerm -e ranger
                ;;
            "--nvim")
                alacritty --config-file "$CONFIG_PATH_ALACRITTY" -e nvim
                ;;
            "--music")
                alacritty --class MusicTerm,MusicTerm -e ncmpcpp
                ;;
            "--fetch")
                alacritty --class FetchTerm,FetchTerm -e ~/.local/bin/sysfetch
                ;;
        esac
        ;;
    "kitty")
        case $1 in
            "--terminal")
                kitty -c "$CONFIG_PATH_KITTY"
                ;;
            "--floating")
                kitty --class=FloaTerm
                ;;
            "--update")
                kitty -c "$CONFIG_PATH_KITTY" --hold --class=FloaTerm -e Updates --update-system 
                ;;
            "--checkupdates")
                kitty -c "$CONFIG_PATH_KITTY" --hold --class=Updating -e Updates --print-updates
                ;;
            "--ranger")
                kitty --hold --class=RangerTerm -e ranger
                ;;
            "--nvim")
                kitty -e nvim
                ;;
            "--music")
                kitty --class=MusicTerm -e ncmpcpp
                ;;
            "--fetch")
                kitty --class=FetchTerm -e ~/.local/bin/sysfetch
                ;;
        esac
        ;;
esac
